apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: hangeul-chat-backend
  
  template:
    metadata:
      labels: 
        app: hangeul-chat-backend
    spec:
      containers:
        - name: hangeul-chat-backend
          image: hangeul-chat-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          envFrom:
            - secretRef:
                name: backend-secret
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 28
          # 실행 중 health check
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3