apiVersion: v1
kind: Service

metadata:
  name: frontend-service

spec:
  type: NodePort
  selector:
    app: hangeul-chat-frontend
  ports:
    - protocol: TCP
      nodePort: 30000
      targetPort: 3000
      port: 3000