apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: hangeul-chat-frontend
  
  template:
    metadata:
      labels: 
        app: hangeul-chat-frontend
    spec:
      containers:
        - name: hangeul-chat-frontend
          image: infrastructure-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000